services:
  app:
    build: .
    image: thyrail/animal-guard-be:latest 
    container_name: animal-guard-api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.animal-guard.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.animal-guard.entrypoints=websecure"
      - "traefik.http.routers.animal-guard.tls.certresolver=le"
      - "traefik.http.services.animal-guard.loadbalancer.server.port=3000"
    networks:
      - proxy

  mongo:
    image: mongo
    container_name: animal-guard-db
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  mongo-data: